version: '3.8'
services:
  bord:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - BIND_ADDRESS=0.0.0.0:3000
      - DATABASE_URL=psql://postgres:insecure@postgres:5432/bord
      - DOCKER_SOCKET=/var/run/docker.sock
      - LOG_LEVEL=bord=debug,sqlx=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=insecure
      - POSTGRES_DB=bord
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
